# Generated by Django 4.2.7 on 2023-11-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scormplayer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="format",
            field=models.IntegerField(
                choices=[(0, "SCORM 1.2"), (1, "SCORM 2004")], default=0
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="index",
            field=models.FileField(default="", max_length=200, upload_to=None),
            preserve_default=False,
        ),
    ]
