# Generated by Django 4.2.7 on 2023-12-05 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scormplayer", "0002_course_format_course_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseuserprogress",
            name="exit_status",
            field=models.CharField(
                choices=[("suspend", "Suspend"), ("", "Restart")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="courseuserprogress",
            name="lesson_status",
            field=models.CharField(
                choices=[("incomplete", "Incomplete"), ("complete", "Complete")],
                default="incomplete",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="courseuserprogress",
            name="score",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scormplayer.score",
            ),
        ),
        migrations.AlterField(
            model_name="courseuserinteraction",
            name="result",
            field=models.CharField(
                choices=[("incorrect", "Incorrect"), ("correct", "Correct")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="score",
            name="max",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="score",
            name="min",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="score",
            name="raw",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="score",
            name="scaled",
            field=models.FloatField(default=1.0),
        ),
    ]
