# Generated by Django 4.2.7 on 2024-01-27 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scormplayer", "0004_courseuserprogress_suspend_data_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courseuserprogress",
            name="lesson_location",
        ),
    ]
