# Generated by Django 4.2.7 on 2024-01-27 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scormplayer", "0005_remove_courseuserprogress_lesson_location"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courseuserinteraction",
            options={
                "verbose_name": "CourseUserInteraction",
                "verbose_name_plural": "CourseUserInteractions",
            },
        ),
    ]
