# Generated by Django 4.2.7 on 2024-03-12 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scormplayer", "0007_alter_course_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Course",
            new_name="ScormCourse",
        ),
    ]
